### Пример работы библиотки

In [1]:
# Для начала нужно загрузить библиотеку
# Для этого нужно добавить её в путь поиска импортов в питоне
import sys
sys.path.append('../build')

In [2]:
# теперь можно импортировать
import simpl
import numpy as np

In [3]:
# Создание симплициального комплекса
K = simpl.SimplicialComplex()

Добавление симплексов

In [4]:
K.AddSimplex([1, 2, 3])
K.AddSimplex([3, 4])
K.AddSimplex([4, 5, 6])
K.AddSimplex([4, 5, 7])
K.AddSimplex([6, 7])
K.AddSimplex([2, 7])

Получение списка максимальных симплексов

In [5]:
K.GetMaxSimplices()

[[1, 2, 3], [2, 7], [3, 4], [4, 5, 6], [4, 5, 7], [6, 7]]

Удаление симплекса

In [6]:
K.RemoveSimplex([1, 2])

In [7]:
K.GetMaxSimplices()

[[1, 3], [2, 3], [2, 7], [3, 4], [4, 5, 6], [4, 5, 7], [6, 7]]

Получение всех симплексов

In [8]:
K.GetAllSimplices()

[[],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [1, 3],
 [2, 3],
 [2, 7],
 [3, 4],
 [4, 5],
 [4, 6],
 [4, 7],
 [5, 6],
 [5, 7],
 [6, 7],
 [4, 5, 6],
 [4, 5, 7]]

Fvector 

In [9]:
K.FVector()

[(0, 7), (1, 10), (2, 2)]

Числа Бетти и Эйлерова характеристика

In [10]:
K.BettiNumber(0)

1

In [11]:
K.BettiNumber(1)

2

In [12]:
K.BettiNumber(2)

0

In [13]:
K.EulerCharacteristic()

-1

Граничный оператор

In [14]:
# по умолчанию возвращается в разреженном виде
B1 = K.BoundaryMatrix(1, 0)
B1.todense()

matrix([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  1,  0,  0,  0,  0,  0,  0,  0],
        [-1, -1,  0,  1,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0, -1,  1,  1,  1,  0,  0,  0],
        [ 0,  0,  0,  0, -1,  0,  0,  1,  1,  0],
        [ 0,  0,  0,  0,  0, -1,  0, -1,  0,  1],
        [ 0,  0, -1,  0,  0,  0, -1,  0, -1, -1]], dtype=int32)

In [15]:
B2 = K.BoundaryMatrix(2, 1)
B2.todense()

matrix([[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 1,  1],
        [-1,  0],
        [ 0, -1],
        [ 1,  0],
        [ 0,  1],
        [ 0,  0]], dtype=int32)

In [16]:
B3 = K.BoundaryMatrix(2, 0)
B3.todense()

matrix([[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 1,  1],
        [-1, -1],
        [ 1,  0],
        [ 0,  1]], dtype=int32)

Лапласиан

In [17]:
K.LaplacianMatrix(1, 0, 2, 0).todense()

matrix([[ 2.,  1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  2.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  0.,  0.,  0.,  1.,  0.,  1.,  1.],
        [-1., -1.,  0.,  2., -1., -1., -1.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  4.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  0.,  3.,  1.,  0.,  0., -1.],
        [ 0.,  0.,  1., -1.,  0.,  1.,  3.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  1., -1.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  3.,  1.],
        [ 0.,  0.,  1.,  0.,  0., -1.,  1., -1.,  1.,  2.]])

In [18]:
K.LaplacianMatrix(1, 0, 2, 1).todense()

matrix([[ 2.,  1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  2.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  0.,  0.,  0.,  1.,  0.,  1.,  1.],
        [-1., -1.,  0.,  2., -1., -1., -1.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  4.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  0.,  3.,  1.,  0.,  0., -1.],
        [ 0.,  0.,  1., -1.,  0.,  1.,  3.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  1., -1.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  3.,  1.],
        [ 0.,  0.,  1.,  0.,  0., -1.,  1., -1.,  1.,  2.]])

In [19]:
# нахождение собственных чисел лапласиана.
# последний параметр регулирует количество
K.EigenValues(1, 0, 2, 1, 100)

[5.548404181092106,
 4.7702229822506546,
 3.999999999999999,
 3.999999999999997,
 3.3547881423517167,
 2.000000000000001,
 1.6628331827684695,
 0.6637515115370554,
 5.555501473735949e-16]

In [20]:
# нахождение всех собственных чисел лапласиана.
K.EigenValuesAll(k=1, p=0, q=2, weighted=True)

[-3.2955250353482206e-16,
 2.5555923642369156e-17,
 0.6637515115370541,
 1.6628331827684697,
 2.0000000000000004,
 3.354788142351716,
 3.999999999999999,
 4.0,
 4.7702229822506546,
 5.548404181092105]

Очищение объекта

In [21]:
K.Clear()

#### Центральность

In [22]:
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

У симплексов можно обновлять веса

In [23]:
K.UpdateWeight([1, 5, 6], 100)
K.UpdateWeight([1, 2, 3], 34)
K.UpdateWeight([1, 2, 4], 89)
K.UpdateWeight([2, 3, 4], 52)


Получение матрицы весов для фиксированного ранга

In [24]:
K.Weights(2)

array([[ 34.,   0.,   0.,   0.,   0.],
       [  0.,  89.,   0.,   0.,   0.],
       [  0.,   0.,   1.,   0.,   0.],
       [  0.,   0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0.,  52.]])

Вычисление невзвешенной closeness

In [25]:
K.ClosenessAll(1, 2, False)

[([1, 2], 0.5208333333333334),
 ([1, 3], 0.5208333333333334),
 ([1, 4], 0.5208333333333334),
 ([1, 5], 0.25),
 ([1, 6], 0.25),
 ([2, 3], 0.5208333333333334),
 ([2, 4], 0.5208333333333334),
 ([3, 4], 0.5208333333333334),
 ([5, 6], 0.25)]

Вычисление взвешенной closeness

In [26]:
K.ClosenessAll(k=1, q=2, weighted=True)

[([1, 2], 0.013950892857142858),
 ([1, 3], 0.025406504065040646),
 ([1, 4], 0.025),
 ([1, 5], 0.0025),
 ([1, 6], 0.0025),
 ([2, 3], 0.01644736842105263),
 ([2, 4], 0.01055743243243243),
 ([3, 4], 0.0252016129032258),
 ([5, 6], 0.0025)]

In [27]:
K.BetweennessAll(1, 2, False)

[([1, 2], 0.017857142857142856),
 ([1, 3], 0.017857142857142856),
 ([1, 4], 0.017857142857142856),
 ([1, 5], 0.0),
 ([1, 6], 0.0),
 ([2, 3], 0.017857142857142856),
 ([2, 4], 0.017857142857142856),
 ([3, 4], 0.017857142857142856),
 ([5, 6], 0.0)]

In [28]:
K.BetweennessAll(1, 2, True)

[([1, 2], 0.0),
 ([1, 3], 0.08035714285714286),
 ([1, 4], 0.0),
 ([1, 5], 0.0),
 ([1, 6], 0.0),
 ([2, 3], 0.017857142857142856),
 ([2, 4], 0.0),
 ([3, 4], 0.05357142857142857),
 ([5, 6], 0.0)]

Степень

In [29]:
K.DegreeAll(2, 3, False)

[3.0, 3.0, 3.0, 0.0, 3.0]

In [30]:
K.DegreeAll(2, 3, True)

[142.0, 87.0, 175.0, 0.0, 124.0]

Комбинаторный комплекс:

In [31]:
comb = simpl.CombinatorialComplex()

comb.Build([[1], [2], [3], [4], [1, 2], [1, 4], [1, 2, 3], [2, 3, 4]])

Инцидентность

In [32]:
print(comb.Incidence([1], 1))
print(comb.Incidence([1], 2))
print(comb.Incidence([1], 3))

print(comb.IncidenceDegree([1], 1))
print(comb.IncidenceDegree([1], 2))
print(comb.IncidenceDegree([1], 3))

[[1, 2], [1, 4]]
[[1, 2, 3]]
[]
2
1
0


Смежность и степень

In [33]:
print(comb.Adjacency([1], 1))
print(comb.Adjacency([1], 2))
print(comb.Adjacency([1], 3))

print(comb.Degree([1], 1, False))
print(comb.Degree([1], 2, False))
print(comb.Degree([1], 3, False))

print(comb.DegreeAll(0, 1, False))
print(comb.DegreeAll(0, 2, False))
print(comb.DegreeAll(0, 3, False))

[[2], [4]]
[[2], [3]]
[]
2.0
2.0
0.0
[2.0, 1.0, 0.0, 1.0]
[2.0, 3.0, 3.0, 2.0]
[0.0, 0.0, 0.0, 0.0]


Количество объектов в комплексе

In [34]:
comb.TotalCount()

8

Граф

In [35]:
graph = simpl.Graph()

Добавление рёбер

In [36]:
graph.AddEdge(1, 2)
graph.AddEdge(1, 3)
graph.AddEdge(2, 3)
graph.AddEdge(4, 5)

Числа Бетти

In [37]:
# number of connected components -- |C|
graph.BettiNumber(0)

2

In [38]:
# |E| - |V| + |C|, where E - edges, V -- vertices
graph.BettiNumber(1)

1

In [39]:
graph.BettiNumber(2)

0

In [40]:
# |E| + |V|
graph.TotalCount()

9

Весовые функции фильтрации:

In [41]:
K.Clear()

In [42]:
def weight(a):
    return len(a) - 1

In [43]:
K.AddFunction("weight", weight)

In [44]:
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

Фильтрация сверху

In [45]:
K.ThresholdAbove("weight", 3)
K.GetMaxSimplices()

[[1, 2, 3], [1, 2, 4], [1, 3, 4], [1, 5, 6], [2, 3, 4]]

In [46]:
K.ThresholdAbove("weight", 2)
K.GetMaxSimplices()

[[1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [3, 4], [5, 6]]

In [47]:
def inverse_weight(a):
    return -(len(a) - 1)

In [48]:
K = simpl.SimplicialComplex()
K.AddFunction("inverse_weight", inverse_weight)
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

Фильтрация снизу

In [49]:
K.ThresholdBelow("inverse_weight", -3)
K.GetMaxSimplices()

[[1, 2, 3], [1, 2, 4], [1, 3, 4], [1, 5, 6], [2, 3, 4]]

In [50]:
K.ThresholdBelow("inverse_weight", -2)
K.GetMaxSimplices()

[[1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [3, 4], [5, 6]]

Пример нетривиальной фильтрации

In [51]:
def bad3(a):
    if 3 in a:
        return 10**9
    return -10**9

In [52]:
K.Clear()
K.AddFunction("bad3", bad3)
K.AddFunction("weight", weight)
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

In [53]:
K.ThresholdAbove("bad3", 5)
K.GetMaxSimplices()

[[1, 2, 4], [1, 5, 6]]

Матрица признаков

In [54]:
K.FeaturesMatrix(2)

[[-1000000000.0, 2.0], [-1000000000.0, 2.0]]

Dowker complex

In [55]:
K.Clear()
K.BuildDowkerComplex([[1, 0, 0], [1, 0, 1], [0, 0, 1]], False)
K.GetMaxSimplices()

[[0, 2]]

In [56]:
K.BuildDowkerComplex([[1, 0, 0], [1, 0, 1], [0, 0, 1]], on_column=True)
K.GetMaxSimplices()

[[0, 1], [1, 2]]

Гиперграф

In [57]:
H = simpl.HyperGraph()
H.AddEdge([1, 2, 3])
H.AddEdge([13, 4])
H.GetEdges()

[[1, 2, 3], [4, 13]]

In [58]:
H.BettiNumber(0)

3

Кликовый комплекс

In [59]:
K.Clear()
K = simpl.SimplicialComplex.CreateCliqueGraph([[0, 1, 1], [1, 0, 1], [1, 1, 0]], 2, 0, 1)
K.GetAllSimplices()

[[1], [2], [0, 1], [0, 2], [1, 2], [0, 1, 2]]

Help

In [60]:
help(K)

Help on SimplicialComplex in module simpl object:

class SimplicialComplex(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      SimplicialComplex
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  AddFunction(...)
 |      AddFunction(self: simpl.SimplicialComplex, name: str, func: Callable[[List[int]], float]) -> None
 |
 |      Add a function on simplices with given name
 |
 |  AddSimplex(...)
 |      AddSimplex(self: simpl.SimplicialComplex, simplex: List[int]) -> None
 |
 |      Add a simplex to the simplicial complex
 |
 |  Adjacency(...)
 |      Adjacency(self: simpl.SimplicialComplex, node: List[int], k: int) -> List[List[int]]
 |
 |      Get all nodes k-adjacence to given node
 |
 |  BettiNumber(...)
 |      BettiNumber(self: simpl.SimplicialComplex, k: int) -> int
 |
 |      Get the k betti number of simplicial complex
 |
 |  Betweenness(...)
 |      Betweenness(self: simpl.SimplicialComplex, node: List[int],

In [61]:
help(K.AddSimplex)

Help on method AddSimplex in module simpl:

AddSimplex(...) method of simpl.SimplicialComplex instance
    AddSimplex(self: simpl.SimplicialComplex, simplex: List[int]) -> None

    Add a simplex to the simplicial complex



In [62]:
H = simpl.HyperGraph()
help(H)

Help on HyperGraph in module simpl object:

class HyperGraph(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      HyperGraph
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  AddEdge(...)
 |      AddEdge(self: simpl.HyperGraph, edge: List[int]) -> None
 |
 |      Add an hyperedge to the hypergraph
 |
 |  AddFunction(...)
 |      AddFunction(self: simpl.HyperGraph, name: str, func: Callable[[List[int]], float]) -> None
 |
 |      Add a function to the hypergraph with the given name
 |
 |  Adjacency(...)
 |      Adjacency(self: simpl.HyperGraph, node: List[int], k: int) -> List[List[int]]
 |
 |      Get all nodes with k-adjacency to the given node
 |
 |  BettiNumber(...)
 |      BettiNumber(self: simpl.HyperGraph, k: int) -> int
 |
 |      Get the k-th Betti number of the hypergraph
 |
 |  Betweenness(...)
 |      Betweenness(self: simpl.HyperGraph, node: List[int], q: int, weighted: bool = False) -> float
 |
 |      