### Пример работы библиотки

In [1]:
# Для начала нужно загрузить библиотеку
# Для этого нужно добавить её в путь поиска импортов в питоне
import sys

In [2]:
sys.path.append('../build/Debug')


In [3]:
# теперь можно импортировать
import simpl
import numpy as np

In [4]:
# Создание симплициального комплекса
K = simpl.SimplicialComplex()

Добавление симплексов

In [5]:
K.AddSimplex([1, 2, 3])
K.AddSimplex([3, 4])
K.AddSimplex([4, 5, 6])
K.AddSimplex([4, 5, 7])
K.AddSimplex([6, 7])
K.AddSimplex([2, 7])

Получение списка максимальных симплексов

In [6]:
K.GetMaxSimplices()

[[1, 2, 3], [2, 7], [3, 4], [4, 5, 6], [4, 5, 7], [6, 7]]

Удаление симплекса

In [7]:
K.RemoveSimplex([1, 2])

In [8]:
K.GetMaxSimplices()

[[1, 3], [2, 3], [2, 7], [3, 4], [4, 5, 6], [4, 5, 7], [6, 7]]

Получение всех симплексов

In [9]:
K.GetAllSimplices()

[[],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [1, 3],
 [2, 3],
 [2, 7],
 [3, 4],
 [4, 5],
 [4, 6],
 [4, 7],
 [5, 6],
 [5, 7],
 [6, 7],
 [4, 5, 6],
 [4, 5, 7]]

Fvector 

In [10]:
K.FVector()

[(0, 7), (1, 10), (2, 2)]

Числа Бетти и Эйлерова характеристика

In [11]:
K.BettiNumber(0)

1

In [12]:
K.BettiNumber(1)

2

In [13]:
K.BettiNumber(2)

0

In [14]:
K.EulerCharacteristic()

-1

Граничный оператор

In [15]:
# по умолчанию возвращается в разреженном виде
B1 = K.BoundaryMatrix(1, 0)
B1.todense()

matrix([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  1,  0,  0,  0,  0,  0,  0,  0],
        [-1, -1,  0,  1,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0, -1,  1,  1,  1,  0,  0,  0],
        [ 0,  0,  0,  0, -1,  0,  0,  1,  1,  0],
        [ 0,  0,  0,  0,  0, -1,  0, -1,  0,  1],
        [ 0,  0, -1,  0,  0,  0, -1,  0, -1, -1]], dtype=int32)

In [16]:
B2 = K.BoundaryMatrix(2, 1)
B2.todense()

matrix([[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 1,  1],
        [-1,  0],
        [ 0, -1],
        [ 1,  0],
        [ 0,  1],
        [ 0,  0]], dtype=int32)

In [17]:
B3 = K.BoundaryMatrix(2, 0)
B3.todense()

matrix([[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 1,  1],
        [-1, -1],
        [ 1,  0],
        [ 0,  1]], dtype=int32)

Лапласиан

In [18]:
K.LaplacianMatrix(1, 0, 2, 0).todense()

matrix([[ 2.,  1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  2.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  0.,  0.,  0.,  1.,  0.,  1.,  1.],
        [-1., -1.,  0.,  2., -1., -1., -1.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  4.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  0.,  3.,  1.,  0.,  0., -1.],
        [ 0.,  0.,  1., -1.,  0.,  1.,  3.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  1., -1.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  3.,  1.],
        [ 0.,  0.,  1.,  0.,  0., -1.,  1., -1.,  1.,  2.]])

In [19]:
K.LaplacianMatrix(1, 0, 2, 1).todense()

matrix([[ 2.,  1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  2.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  0.,  0.,  0.,  1.,  0.,  1.,  1.],
        [-1., -1.,  0.,  2., -1., -1., -1.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  4.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  0.,  3.,  1.,  0.,  0., -1.],
        [ 0.,  0.,  1., -1.,  0.,  1.,  3.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  1., -1.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  3.,  1.],
        [ 0.,  0.,  1.,  0.,  0., -1.,  1., -1.,  1.,  2.]])

In [20]:
K.LaplacianMatrix(1, 0, 2, True, False).todense()

matrix([[ 2.,  1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  2.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  0.,  0.,  0.,  1.,  0.,  1.,  1.],
        [-1., -1.,  0.,  2., -1., -1., -1.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  4.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  0.,  3.,  1.,  0.,  0., -1.],
        [ 0.,  0.,  1., -1.,  0.,  1.,  3.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  1., -1.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  3.,  1.],
        [ 0.,  0.,  1.,  0.,  0., -1.,  1., -1.,  1.,  2.]])

In [21]:
# Нахождение собственных чисел лапласиана.
K.EigenValues(1, 0, 2, True, False, 2, "sm")

([-1.3325095189673759e-15, -4.941914443518075e-17],
 [[-4.823249453060881e-16, 1.662269569590115e-16],
  [-0.06008203812773589, -0.5311350434764245],
  [0.060082038127736596, 0.5311350434764243],
  [-0.06008203812773612, -0.5311350434764242],
  [-0.015020509531934153, -0.13278376086910604],
  [-0.36633331893945836, -0.09304322808213336],
  [0.32127179034365627, -0.3053080545251848],
  [-0.35131280940752474, 0.03974053278697269],
  [0.3362922998755905, -0.1725242936560788],
  [-0.7176461283469832, -0.053302695295160706]])

In [22]:
# нахождение всех собственных чисел лапласиана.
K.EigenValuesAll(k=1, p=0, q=2, weighted=True, normalize=True)

([2.676783379767847e-16,
  5.016714911204086e-16,
  0.6424303018152311,
  1.611022500038123,
  2.0,
  2.216945176373858,
  3.436171484685268,
  4.000000000000001,
  4.639837264122522,
  5.453593272964995],
 [[5.912521690044935e-17,
   1.001342947996102e-16,
   0.6208390602189252,
   0.5019682794882838,
   -2.44689909166216e-16,
   0.0973775050739883,
   0.5358033179373778,
   -3.190697258334709e-16,
   -0.1609842969225086,
   -0.20025780841525992],
  [0.40377314409129467,
   0.34302915691905206,
   -0.3127878589193908,
   -0.39100462744345577,
   6.916759832302315e-17,
   0.28406152290219816,
   0.5446663001965883,
   -1.3135929970982112e-16,
   -0.0777930408481207,
   -0.29184464647601394],
  [-0.4037731440912947,
   -0.3430291569190521,
   0.333836695693462,
   -0.5456265380597419,
   -1.3877787807814457e-16,
   0.22718421500213212,
   0.021591744649160874,
   3.1553600361991144e-16,
   0.30280263390871565,
   -0.40789052587950836],
  [0.4037731440912946,
   0.3430291569190522,
   0.

Очищение объекта

In [23]:
K.Clear()

#### Центральность

In [24]:
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

У симплексов можно обновлять веса

In [25]:
K.UpdateWeight([1, 5, 6], 100)
K.UpdateWeight([1, 2, 3], 34)
K.UpdateWeight([1, 2, 4], 89)
K.UpdateWeight([2, 3, 4], 52)


Получение матрицы весов для фиксированного ранга

In [26]:
K.Weights(2)

array([[ 34.,   0.,   0.,   0.,   0.],
       [  0.,  89.,   0.,   0.,   0.],
       [  0.,   0.,   1.,   0.,   0.],
       [  0.,   0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0.,  52.]])

In [27]:
K.GetSimplicesWithDimension(1)

[[1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [3, 4], [5, 6]]

In [28]:
K.AdjacencyMatrix(1, 0, 2, False)

[[0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

Вычисление невзвешенной closeness

In [29]:
K.ClosenessAll(1, 2, False)

[([1, 2], 0.3333333333333333),
 ([1, 3], 0.3333333333333333),
 ([1, 4], 0.3333333333333333),
 ([1, 5], 0.4),
 ([1, 6], 0.4),
 ([2, 3], 0.0),
 ([2, 4], 0.0),
 ([3, 4], 0.0),
 ([5, 6], 0.0)]

Вычисление взвешенной closeness

In [30]:
K.ClosenessAll(k=1, q=2, weighted=True)

[([1, 2], 0.3333333333333333),
 ([1, 3], 0.3333333333333333),
 ([1, 4], 0.3333333333333333),
 ([1, 5], 0.4),
 ([1, 6], 0.4),
 ([2, 3], 0.0),
 ([2, 4], 0.0),
 ([3, 4], 0.0),
 ([5, 6], 0.0)]

In [31]:
K.BetweennessAll(1, 2, False)

[([1, 2], 0.011904761904761904),
 ([1, 3], 0.011904761904761904),
 ([1, 4], 0.011904761904761904),
 ([1, 5], 0.05357142857142857),
 ([1, 6], 0.05357142857142857),
 ([2, 3], 0.0),
 ([2, 4], 0.0),
 ([3, 4], 0.0),
 ([5, 6], 0.0)]

In [32]:
K.BetweennessAll(1, 2, True)

[([1, 2], 0.011904761904761904),
 ([1, 3], 0.011904761904761904),
 ([1, 4], 0.011904761904761904),
 ([1, 5], 0.05357142857142857),
 ([1, 6], 0.05357142857142857),
 ([2, 3], 0.0),
 ([2, 4], 0.0),
 ([3, 4], 0.0),
 ([5, 6], 0.0)]

Степень

In [33]:
K.DegreeAll(2, 3, False)

[1.0, 1.0, 1.0, 0.0, 1.0]

In [34]:
K.DegreeAll(2, 3, True)

[1.0, 1.0, 1.0, 0.0, 1.0]

Комбинаторный комплекс:

In [35]:
comb = simpl.CombinatorialComplex()

comb.Build([[1], [2], [3], [4], [1, 2], [1, 4], [1, 2, 3], [2, 3, 4]])

Инцидентность

In [36]:
print(comb.Incidence([1], 1))
print(comb.Incidence([1], 2))
print(comb.Incidence([1], 3))


[[1, 2], [1, 4]]
[[1, 2, 3]]
[]


Смежность и степень

In [37]:
print(comb.Adjacency([1], 1))
print(comb.Adjacency([1], 2))
print(comb.Adjacency([1], 3))

print(comb.Degree([1], 1, False))
print(comb.Degree([1], 2, False))
print(comb.Degree([1], 3, False))

print(comb.DegreeAll(0, 1, False))
print(comb.DegreeAll(0, 2, False))
print(comb.DegreeAll(0, 3, False))

[[2], [4]]
[[2], [3]]
[]
2.0
1.0
0.0
[2.0, 1.0, 0.0, 1.0]
[1.0, 2.0, 2.0, 1.0]
[0.0, 0.0, 0.0, 0.0]


Количество объектов в комплексе

In [38]:
comb.TotalCount()

8

Граф

In [39]:
graph = simpl.Graph()

Добавление рёбер

In [40]:
graph.AddEdge(1, 2)
graph.AddEdge(1, 3)
graph.AddEdge(2, 3)
graph.AddEdge(4, 5)

Числа Бетти

In [41]:
# number of connected components -- |C|
graph.BettiNumber(0)

2

In [42]:
# |E| - |V| + |C|, where E - edges, V -- vertices
graph.BettiNumber(1)

1

In [43]:
graph.BettiNumber(2)

0

In [44]:
# |E| + |V|
graph.TotalCount()

9

Весовые функции фильтрации:

In [45]:
K.Clear()

In [46]:
def weight(a):
    return len(a) - 1

In [47]:
K.AddFunction("weight", weight)

In [48]:
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

Фильтрация сверху

In [49]:
K.ThresholdAbove("weight", 3)
K.GetMaxSimplices()

[[1, 2, 3], [1, 2, 4], [1, 3, 4], [1, 5, 6], [2, 3, 4]]

In [50]:
K.ThresholdAbove("weight", 2)
K.GetMaxSimplices()

[[1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [3, 4], [5, 6]]

In [51]:
def inverse_weight(a):
    return -(len(a) - 1)

In [52]:
K = simpl.SimplicialComplex()
K.AddFunction("inverse_weight", inverse_weight)
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

Фильтрация снизу

In [53]:
K.ThresholdBelow("inverse_weight", -3)
K.GetMaxSimplices()

[[1, 2, 3], [1, 2, 4], [1, 3, 4], [1, 5, 6], [2, 3, 4]]

In [54]:
K.ThresholdBelow("inverse_weight", -2)
K.GetMaxSimplices()

[[1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [3, 4], [5, 6]]

Пример нетривиальной фильтрации

In [55]:
def bad3(a):
    if 3 in a:
        return 10**9
    return -10**9

In [56]:
K.Clear()
K.AddFunction("bad3", bad3)
K.AddFunction("weight", weight)
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

In [57]:
K.ThresholdAbove("bad3", 5)
K.GetMaxSimplices()

[[1, 2, 4], [1, 5, 6]]

Матрица признаков

In [58]:
K.FeaturesMatrix(2)

[[-1000000000.0, 2.0], [-1000000000.0, 2.0]]

Dowker complex

In [59]:
K.Clear()
K.BuildDowkerComplex([[1, 0, 0], [1, 0, 1], [0, 0, 1]], False)
K.GetMaxSimplices()

[[0, 2]]

In [60]:
K.BuildDowkerComplex([[1, 0, 0], [1, 0, 1], [0, 0, 1]], on_column=True)
K.GetMaxSimplices()

[[0, 1], [1, 2]]

Гиперграф

In [61]:
H = simpl.HyperGraph()
H.AddEdge([1, 2, 3])
H.AddEdge([13, 4])
H.GetEdges()

[[1, 2, 3], [4, 13]]

In [62]:
H.BettiNumber(0)

3

Кликовый комплекс

In [63]:
K.Clear()
K = simpl.SimplicialComplex.CreateCliqueGraph([[0, 1, 1], [1, 0, 1], [1, 1, 0]], 2, 0, 1)
K.GetAllSimplices()

[[1], [2], [0, 1], [0, 2], [1, 2], [0, 1, 2]]

Help

In [64]:
help(K)

Help on SimplicialComplex in module simpl object:

class SimplicialComplex(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      SimplicialComplex
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  AddFunction(...)
 |      AddFunction(self: simpl.SimplicialComplex, name: str, func: Callable[[list[int]], float]) -> None
 |
 |      Add a function on simplices with given name
 |
 |  AddSimplex(...)
 |      AddSimplex(self: simpl.SimplicialComplex, simplex: list[int]) -> None
 |
 |      Add a simplex to the simplicial complex
 |
 |  Adjacency(...)
 |      Adjacency(self: simpl.SimplicialComplex, node: list[int], k: int) -> list[list[int]]
 |
 |      Get all nodes k-adjacence to given node
 |
 |  AdjacencyMatrix(...)
 |      AdjacencyMatrix(self: simpl.SimplicialComplex, k: int, p: int, q: int, weighted: bool = False) -> list[list[float]]
 |
 |      Get all nodes adjacency matrix
 |
 |  BettiNumber(...)
 |      BettiNumber

In [65]:
help(K.AddSimplex)

Help on method AddSimplex in module simpl:

AddSimplex(...) method of simpl.SimplicialComplex instance
    AddSimplex(self: simpl.SimplicialComplex, simplex: list[int]) -> None

    Add a simplex to the simplicial complex



In [66]:
H = simpl.HyperGraph()
help(H)

Help on HyperGraph in module simpl object:

class HyperGraph(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      HyperGraph
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  AddEdge(...)
 |      AddEdge(self: simpl.HyperGraph, edge: list[int]) -> None
 |
 |      Add an hyperedge to the hypergraph
 |
 |  AddFunction(...)
 |      AddFunction(self: simpl.HyperGraph, name: str, func: Callable[[list[int]], float]) -> None
 |
 |      Add a function to the hypergraph with the given name
 |
 |  Adjacency(...)
 |      Adjacency(self: simpl.HyperGraph, node: list[int], k: int) -> list[list[int]]
 |
 |      Get all nodes with k-adjacency to the given node
 |
 |  AdjacencyMatrix(...)
 |      AdjacencyMatrix(self: simpl.HyperGraph, k: int, p: int, q: int, weighted: bool = False) -> list[list[float]]
 |
 |      Get all nodes adjacency matrix
 |
 |  BettiNumber(...)
 |      BettiNumber(self: simpl.HyperGraph, k: int) -> int
 |
 |

## Testing exp and eig centralities

In [67]:
sc = simpl.SimplicialComplex()

In [68]:
edges = [(1,2), (1,3), (1,4), (2,3), (2,4), (3,4), 
         (3,5), (4,5), (4,6), (5,6), (6,7), (6,8), (7,8), (6, 9)]
triangles = [
    (1,2,3), (1,2,4), (1,3,4), (2,3,4),
    (3,4,5), (4,5,6), (6,7,8)
]

In [69]:
for edge in edges:
    sc.AddSimplex(edge)

In [70]:
for triangle in triangles:
    sc.AddSimplex(triangle)

In [71]:
sc.AdjacencyMatrix(1, 0, 2)

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

In [72]:
sc.ClosenessSubgraph(1, 2)

[([1, 2], 1.0),
 ([1, 3], 1.6445932159362215),
 ([1, 4], 2.7144722245343416),
 ([2, 3], 1.6445932159362215),
 ([2, 4], 2.7144722245343416),
 ([3, 4], 1.8953669259533783),
 ([3, 5], 3.1645035545752496),
 ([4, 5], 2.4149077088196016),
 ([4, 6], 8.883561153156622),
 ([5, 6], 6.361587353098786),
 ([6, 7], 5.602251936576013),
 ([6, 8], 5.602251936576011),
 ([6, 9], 7.821471071553865),
 ([7, 8], 1.0)]

[([1, 2], 1.0),
 ([1, 3], 1.6445932159362215),
 ([1, 4], 2.7144722245343416),
 ([2, 3], 1.6445932159362215),
 ([2, 4], 2.7144722245343416),
 ([3, 4], 1.8953669259533783),
 ([3, 5], 3.1645035545752496),
 ([4, 5], 2.4149077088196016),
 ([4, 6], 8.883561153156622),
 ([5, 6], 6.361587353098786),
 ([6, 7], 5.602251936576013),
 ([6, 8], 5.602251936576011),
 ([6, 9], 7.821471071553865),
 ([7, 8], 1.0)]

In [73]:
g = simpl.Graph()
g.AddEdge(1, 2)
g.UpdateWeight([1, 2], 3)

In [74]:
g.DegreeAll(0, 1, True)

[3.0, 3.0]

In [75]:
g.HodgeDecomposition(0, -1, 1, [1, 2])

([0.0, 0.0], [1.0, 2.0], [0.0, 0.0])