In [58]:
print('Example of library!')

Example of library!


In [59]:
# should run after cmake build
import sys
sys.path.append('../build')

In [60]:
import simpl

In [61]:
K = simpl.SimplicialComplex()

Addition and removal симплексов

In [62]:
K.AddSimplex([1, 2, 3])
K.AddSimplex([3, 4])
K.AddSimplex([4, 5, 6])
K.AddSimplex([4, 5, 7])
K.AddSimplex([6, 7])
K.AddSimplex([2, 7])

In [63]:
K.GetMaxSimplices()

[[1, 2, 3], [2, 7], [3, 4], [4, 5, 6], [4, 5, 7], [6, 7]]

In [64]:
K.RemoveSimplex([1, 2])

In [65]:
K.GetMaxSimplices()

[[1, 3], [2, 3], [2, 7], [3, 4], [4, 5, 6], [4, 5, 7], [6, 7]]

In [66]:
K.FVector()

[(0, 7), (1, 10), (2, 2)]

In [67]:
K.BettiNumber(0)

1

In [68]:
K.BettiNumber(1)

2

In [69]:
K.BettiNumber(2)

0

In [70]:
K.EulerCharacteristic()

-1

Boundary

In [71]:
K.GetAll()

[[],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [1, 3],
 [2, 3],
 [2, 7],
 [3, 4],
 [4, 5],
 [4, 6],
 [4, 7],
 [5, 6],
 [5, 7],
 [6, 7],
 [4, 5, 6],
 [4, 5, 7]]

In [72]:
B1 = K.BoundaryMatrix(1, 0)
B1

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [-1, -1, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, -1, 1, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, -1, 0, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, -1, 0, -1, 0, 1],
 [0, 0, -1, 0, 0, 0, -1, 0, -1, -1]]

In [73]:
B2 = K.BoundaryMatrix(2, 1)
B2

[[0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [1, 1],
 [-1, 0],
 [0, -1],
 [1, 0],
 [0, 1],
 [0, 0]]

In [74]:
K.BoundaryMatrix(2, 0)

[[0, 0], [0, 0], [0, 0], [1, 1], [-1, -1], [1, 0], [0, 1]]

In [75]:
import numpy as np
B1 = np.array(K.BoundaryMatrix(1, 0))
B2 = np.array(K.BoundaryMatrix(2, 1))

L1_upper = B2 @ B2.T
L1_lower = B1.T @ B1

L1 = L1_upper + L1_lower
L1

array([[ 2,  1,  0, -1,  0,  0,  0,  0,  0,  0],
       [ 1,  2,  1, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  0,  0,  0,  1,  0,  1,  1],
       [-1, -1,  0,  2, -1, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  4,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  3,  1,  0,  0, -1],
       [ 0,  0,  1, -1,  0,  1,  3,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  1, -1],
       [ 0,  0,  1,  0,  0,  0,  0,  1,  3,  1],
       [ 0,  0,  1,  0,  0, -1,  1, -1,  1,  2]])

In [76]:
K.LaplacianMatrix(1, 0, 2, 0) - L1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [77]:
K.Weights(3)

[]

In [78]:
K.LaplacianMatrix(1, 0, 2, 1) - L1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
np.linalg.eigh(L1)[0]

array([-4.84814023e-16,  1.83226048e-15,  6.63751512e-01,  1.66283318e+00,
        2.00000000e+00,  3.35478814e+00,  4.00000000e+00,  4.00000000e+00,
        4.77022298e+00,  5.54840418e+00])

In [80]:
K.EigenValues(1, 0, 2, 1)

[-4.5144157831232065e-16,
 4.1120552396043855e-16,
 0.6637515115370547,
 1.6628331827684684,
 1.999999999999999,
 3.354788142351714,
 4.000000000000001,
 4.000000000000002,
 4.770222982250656,
 5.548404181092106]

Centrality:

In [81]:
K.Clear()

In [82]:
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

In [83]:
K.UpdateWeight([1, 5, 6], 100)
K.UpdateWeight([1, 2, 3], 100)

In [84]:
K.Weights(2)

[[100.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 100.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0]]

In [85]:
K.ClosenessAll(1, 2, False)

[([1, 2], 0.5208333333333334),
 ([1, 3], 0.5208333333333334),
 ([1, 4], 0.5208333333333334),
 ([1, 5], 0.25),
 ([1, 6], 0.25),
 ([2, 3], 0.5208333333333334),
 ([2, 4], 0.5208333333333334),
 ([3, 4], 0.5208333333333334),
 ([5, 6], 0.25)]

In [86]:
K.BetweennessAll(1, 2, True)

[([1, 2], 0.017857142857142856),
 ([1, 3], 0.017857142857142856),
 ([1, 4], 0.017857142857142856),
 ([1, 5], 0.0),
 ([1, 6], 0.0),
 ([2, 3], 0.017857142857142856),
 ([2, 4], 0.017857142857142856),
 ([3, 4], 0.017857142857142856),
 ([5, 6], 0.0),
 ([1, 2], 0.017857142857142856),
 ([1, 3], 0.017857142857142856),
 ([1, 4], 0.017857142857142856),
 ([1, 5], 0.0),
 ([1, 6], 0.0),
 ([2, 3], 0.017857142857142856),
 ([2, 4], 0.017857142857142856),
 ([3, 4], 0.017857142857142856),
 ([5, 6], 0.0)]

In [87]:
K.ClosenessAll(1, 2, True)

[([1, 2], 0.5208333333333334),
 ([1, 3], 0.5208333333333334),
 ([1, 4], 0.5208333333333334),
 ([1, 5], 0.25),
 ([1, 6], 0.25),
 ([2, 3], 0.5208333333333334),
 ([2, 4], 0.5208333333333334),
 ([3, 4], 0.5208333333333334),
 ([5, 6], 0.25)]

Комбинаторный комплекс:

In [88]:
comb = simpl.CombinatorialComplex()

comb.Build([[1], [2], [3], [4], [1, 2], [1, 4], [1, 2, 3], [2, 3, 4]])

In [89]:
print(comb.Incidence([1], 1))
print(comb.Incidence([1], 2))
print(comb.Incidence([1], 3))

print(comb.IncidenceDegree([1], 1))
print(comb.IncidenceDegree([1], 2))
print(comb.IncidenceDegree([1], 3))

[[1, 2], [1, 4]]
[[1, 2, 3]]
[]
2
1
0


In [90]:
print(comb.Adjacency([1], 1))
print(comb.Adjacency([1], 2))
print(comb.Adjacency([1], 3))

print(comb.Degree([1], 1, False))
print(comb.Degree([1], 2, False))
print(comb.Degree([1], 3, False))

print(comb.DegreeAll(0, 1, False))
print(comb.DegreeAll(0, 2, False))
print(comb.DegreeAll(0, 3, False))

[[2], [4]]
[[2], [3]]
[]
2.0
2.0
0.0
[2.0, 1.0, 0.0, 1.0]
[2.0, 3.0, 3.0, 2.0]
[0.0, 0.0, 0.0, 0.0]


In [91]:
comb.TotalCount()

8

Граф:

In [92]:
graph = simpl.Graph()

In [93]:
graph.AddEdge(1, 2)
graph.AddEdge(1, 3)
graph.AddEdge(2, 3)
graph.AddEdge(4, 5)

In [94]:
# number of connected components -- |C|
graph.BettiNumber(0)

2

In [95]:
# |E| - |V| + |C|, where E - edges, V -- vertices
graph.BettiNumber(1)

1

In [96]:
graph.BettiNumber(2)

0

In [97]:
# |E| + |V|
graph.TotalCount()

9

Весовые функции:

In [98]:
K.Clear()

In [99]:
def weight(a):
    return len(a) - 1

In [100]:
K.AddFunction("weight", weight)

In [101]:
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

In [102]:
K.ThresholdAbove("weight", 3)
K.GetMaxSimplices()

[[1, 2, 3], [1, 2, 4], [1, 3, 4], [1, 5, 6], [2, 3, 4]]

In [103]:
K.ThresholdAbove("weight", 2)
K.GetMaxSimplices()

[[1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [3, 4], [5, 6]]

In [104]:
def inverse_weight(a):
    return -(len(a) - 1)
K = simpl.SimplicialComplex()
K.AddFunction("inverse_weight", inverse_weight)
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

In [105]:
K.ThresholdBelow("inverse_weight", -3)
K.GetMaxSimplices()

[[1, 2, 3], [1, 2, 4], [1, 3, 4], [1, 5, 6], [2, 3, 4]]

In [106]:
K.ThresholdBelow("inverse_weight", -2)
K.GetMaxSimplices()

[[1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [3, 4], [5, 6]]

In [107]:
def bad3(a):
    if 3 in a:
        return 10**9
    return -10**9

In [108]:
K.Clear()
K.AddFunction("bad3", bad3)
K.AddFunction("weight", weight)
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

In [109]:
K.FeaturesMatrix(2)

[[1000000000.0, 2.0],
 [-1000000000.0, 2.0],
 [1000000000.0, 2.0],
 [-1000000000.0, 2.0],
 [1000000000.0, 2.0]]

In [110]:
K.ThresholdAbove("bad3", 5)
K.GetMaxSimplices()

[[1, 2, 4], [1, 5, 6]]

Dowker complex

In [111]:
K.Clear()
K.BuildFromDowkerComplex([[1, 0, 0], [1, 0, 1], [0, 0, 1]], False)
K.GetMaxSimplices()

[[0, 2]]

In [112]:
K.BuildFromDowkerComplex([[1, 0, 0], [1, 0, 1], [0, 0, 1]], True)
K.GetMaxSimplices()

[[0, 1], [1, 2]]

In [113]:
H = simpl.HyperGraph()
H.AddEdge([1, 2, 3])
H.AddEdge([13, 4])
H.GetEdges()

[[1, 2, 3], [4, 13]]

In [114]:
K.Clear()