In [4]:
print('Example of library!')

Example of library!


In [5]:
# should run after cmake build
import sys
sys.path.append('../build')

In [6]:
import simpl

In [7]:
K = simpl.SimplicialComplex()

Addition and removal симплексов

In [8]:
K.AddSimplex([1, 2, 3])
K.AddSimplex([3, 4])
K.AddSimplex([4, 5, 6])
K.AddSimplex([4, 5, 7])
K.AddSimplex([6, 7])
K.AddSimplex([2, 7])

In [9]:
K.GetMaxSimplices()

[[1, 2, 3], [2, 7], [3, 4], [4, 5, 6], [4, 5, 7], [6, 7]]

In [10]:
K.RemoveSimplex([1, 2])

In [11]:
K.GetMaxSimplices()

[[1, 3], [2, 3], [2, 7], [3, 4], [4, 5, 6], [4, 5, 7], [6, 7]]

In [12]:
K.FVector()

[(0, 7), (1, 10), (2, 2)]

In [13]:
K.BettiNumber(0)

1

In [14]:
K.BettiNumber(1)

2

In [15]:
K.BettiNumber(2)

0

In [16]:
K.EulerCharacteristic()

-1

Boundary

In [17]:
K.GetAll()

[[],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [1, 3],
 [2, 3],
 [2, 7],
 [3, 4],
 [4, 5],
 [4, 6],
 [4, 7],
 [5, 6],
 [5, 7],
 [6, 7],
 [4, 5, 6],
 [4, 5, 7]]

In [18]:
B1 = K.BoundaryMatrix(1, 0)
B1

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [-1, -1, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, -1, 1, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, -1, 0, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, -1, 0, -1, 0, 1],
 [0, 0, -1, 0, 0, 0, -1, 0, -1, -1]]

In [19]:
B2 = K.BoundaryMatrix(2, 1)
B2

[[0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [1, 1],
 [-1, 0],
 [0, -1],
 [1, 0],
 [0, 1],
 [0, 0]]

In [20]:
K.BoundaryMatrix(2, 0)

[[0, 0], [0, 0], [0, 0], [1, 1], [-1, -1], [1, 0], [0, 1]]

In [21]:
import numpy as np
B1 = np.array(K.BoundaryMatrix(1, 0))
B2 = np.array(K.BoundaryMatrix(2, 1))

L1_upper = B2 @ B2.T
L1_lower = B1.T @ B1

L1 = L1_upper + L1_lower
L1

array([[ 2,  1,  0, -1,  0,  0,  0,  0,  0,  0],
       [ 1,  2,  1, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  0,  0,  0,  1,  0,  1,  1],
       [-1, -1,  0,  2, -1, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  4,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  3,  1,  0,  0, -1],
       [ 0,  0,  1, -1,  0,  1,  3,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  1, -1],
       [ 0,  0,  1,  0,  0,  0,  0,  1,  3,  1],
       [ 0,  0,  1,  0,  0, -1,  1, -1,  1,  2]])

In [22]:
K.LaplacianMatrix(1, 0, 2, 0) - L1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
K.Weights(3)

[]

In [24]:
K.LaplacianMatrix(1, 0, 2, 1) - L1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.linalg.eigh(L1)[0]

array([-4.84814023e-16,  1.83226048e-15,  6.63751512e-01,  1.66283318e+00,
        2.00000000e+00,  3.35478814e+00,  4.00000000e+00,  4.00000000e+00,
        4.77022298e+00,  5.54840418e+00])

In [26]:
K.EigenValues(1, 0, 2, 1)

[-4.5144157831232065e-16,
 4.1120552396043855e-16,
 0.6637515115370547,
 1.6628331827684684,
 1.999999999999999,
 3.354788142351714,
 4.000000000000001,
 4.000000000000002,
 4.770222982250656,
 5.548404181092106]

Centrality:

In [27]:
K.Clear()

In [28]:
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

In [29]:
K.UpdateWeight([1, 5, 6], 100)
K.UpdateWeight([1, 2, 3], 100)

In [30]:
K.Weights(2)

[[100.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 100.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0]]

In [31]:
K.ClosenessAll(1, 2, False)

[([1, 2], 0.5208333333333334),
 ([1, 3], 0.5208333333333334),
 ([1, 4], 0.5208333333333334),
 ([1, 5], 0.25),
 ([1, 6], 0.25),
 ([2, 3], 0.5208333333333334),
 ([2, 4], 0.5208333333333334),
 ([3, 4], 0.5208333333333334),
 ([5, 6], 0.25)]

In [32]:
K.BetweennessAll(1, 2, True)

[([1, 2], 0.017857142857142856),
 ([1, 3], 0.017857142857142856),
 ([1, 4], 0.017857142857142856),
 ([1, 5], 0.0),
 ([1, 6], 0.0),
 ([2, 3], 0.017857142857142856),
 ([2, 4], 0.017857142857142856),
 ([3, 4], 0.017857142857142856),
 ([5, 6], 0.0)]

In [33]:
K.ClosenessAll(1, 2, True)

[([1, 2], 0.5208333333333334),
 ([1, 3], 0.5208333333333334),
 ([1, 4], 0.5208333333333334),
 ([1, 5], 0.25),
 ([1, 6], 0.25),
 ([2, 3], 0.5208333333333334),
 ([2, 4], 0.5208333333333334),
 ([3, 4], 0.5208333333333334),
 ([5, 6], 0.25)]

Комбинаторный комплекс:

In [34]:
comb = simpl.CombinatorialComplex()

comb.Build([[1], [2], [3], [4], [1, 2], [1, 4], [1, 2, 3], [2, 3, 4]])

In [35]:
print(comb.Incidence([1], 1))
print(comb.Incidence([1], 2))
print(comb.Incidence([1], 3))

print(comb.IncidenceDegree([1], 1))
print(comb.IncidenceDegree([1], 2))
print(comb.IncidenceDegree([1], 3))

[[1, 2], [1, 4]]
[[1, 2, 3]]
[]
2
1
0


In [36]:
print(comb.Adjacency([1], 1))
print(comb.Adjacency([1], 2))
print(comb.Adjacency([1], 3))

print(comb.Degree([1], 1, False))
print(comb.Degree([1], 2, False))
print(comb.Degree([1], 3, False))

print(comb.DegreeAll(0, 1, False))
print(comb.DegreeAll(0, 2, False))
print(comb.DegreeAll(0, 3, False))

[[2], [4]]
[[2], [3]]
[]
2.0
2.0
0.0
[2.0, 1.0, 0.0, 1.0]
[2.0, 3.0, 3.0, 2.0]
[0.0, 0.0, 0.0, 0.0]


In [37]:
comb.TotalCount()

8

Граф:

In [38]:
graph = simpl.Graph()

In [39]:
graph.AddEdge(1, 2)
graph.AddEdge(1, 3)
graph.AddEdge(2, 3)
graph.AddEdge(4, 5)

In [40]:
# number of connected components -- |C|
graph.BettiNumber(0)

2

In [41]:
# |E| - |V| + |C|, where E - edges, V -- vertices
graph.BettiNumber(1)

1

In [42]:
graph.BettiNumber(2)

0

In [43]:
# |E| + |V|
graph.TotalCount()

9

Весовые функции:

In [44]:
K.Clear()

In [45]:
def weight(a):
    return len(a) - 1

In [46]:
K.AddFunction("weight", weight)

In [47]:
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

In [48]:
K.ThresholdAbove("weight", 3)
K.GetMaxSimplices()

[[1, 2, 3], [1, 2, 4], [1, 3, 4], [1, 5, 6], [2, 3, 4]]

In [49]:
K.ThresholdAbove("weight", 2)
K.GetMaxSimplices()

[[1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [3, 4], [5, 6]]

In [50]:
def inverse_weight(a):
    return -(len(a) - 1)
K = simpl.SimplicialComplex()
K.AddFunction("inverse_weight", inverse_weight)
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

In [51]:
K.ThresholdBelow("inverse_weight", -3)
K.GetMaxSimplices()

[[1, 2, 3], [1, 2, 4], [1, 3, 4], [1, 5, 6], [2, 3, 4]]

In [52]:
K.ThresholdBelow("inverse_weight", -2)
K.GetMaxSimplices()

[[1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [3, 4], [5, 6]]

In [53]:
def bad3(a):
    if 3 in a:
        return 10**9
    return -10**9

In [54]:
K.Clear()
K.AddFunction("bad3", bad3)
K.AddFunction("weight", weight)
K.AddSimplex([1, 2, 3, 4])
K.AddSimplex([1, 5, 6])

In [55]:
K.FeaturesMatrix(2)

[[1000000000.0, 2.0],
 [-1000000000.0, 2.0],
 [1000000000.0, 2.0],
 [-1000000000.0, 2.0],
 [1000000000.0, 2.0]]

In [56]:
K.ThresholdAbove("bad3", 5)
K.GetMaxSimplices()

[[1, 2, 4], [1, 5, 6]]

Dowker complex

In [57]:
K.Clear()
K.BuildFromDowkerComplex([[1, 0, 0], [1, 0, 1], [0, 0, 1]], False)
K.GetMaxSimplices()

[[0, 2]]

In [58]:
K.BuildFromDowkerComplex([[1, 0, 0], [1, 0, 1], [0, 0, 1]], True)
K.GetMaxSimplices()

[[0, 1], [1, 2]]

In [59]:
H = simpl.HyperGraph()
H.AddEdge([1, 2, 3])
H.AddEdge([13, 4])
H.GetEdges()

[[1, 2, 3], [4, 13]]

In [60]:
K.Clear()

Help

In [61]:
help(K.AddSimplex)

Help on method AddSimplex in module simpl:

AddSimplex(...) method of simpl.SimplicialComplex instance
    AddSimplex(self: simpl.SimplicialComplex, simplex: List[int]) -> None

